--CREATE PAYMENT_DIM TABLE
IF OBJECT_ID('DBO.PAYMENT_DIM') IS NOT NULL BEGIN DROP EXTERNAL TABLE DBO.PAYMENT_DIM;

END CREATE EXTERNAL TABLE [DBO].[PAYMENT_DIM] WITH (
    LOCATION = 'Star_schema/PAYMENT_DIM',
    DATA_SOURCE = [AzureStorage],
    FILE_FORMAT = [TextFileFormat]
) AS (
    SELECT
        PAYMENT_ID,
        DATE,
        RIDER_ID,
        AMOUNT,
        DATEPART(DAY, CONVERT(DATE, DATE)) AS DAY,
        DATEPART(MONTH, CONVERT(DATE, DATE)) AS MONTH,
        DATEPART(QUARTER, CONVERT(DATE, DATE)) AS QUARTER,
        DATEPART(YEAR, CONVERT(DATE, DATE)) AS YEAR,
        DATEPART(DAYOFYEAR, CONVERT(DATE, DATE)) AS DAY_OF_YEAR,
        DATEPART(WEEKDAY, CONVERT(DATE, DATE)) AS DAY_OF_WEEK
    FROM
        dbo.STAGING_PAYMENT
);

GO
SELECT
    TOP 10 *
FROM
    [DBO].[PAYMENT_DIM];