-- CREATE RIDER_DIM TABLE
IF OBJECT_ID('DBO.RIDER_DIM') IS NOT NULL BEGIN DROP EXTERNAL TABLE DBO.RIDER_DIM
END CREATE EXTERNAL TABLE [DBO].[RIDER_DIM] WITH (
    LOCATION = 'Star_schema/RIDER_DIM',
    DATA_SOURCE = [AzureStorage],
    FILE_FORMAT = [TextFileFormat]
) AS
SELECT
    [RIDER_ID],
    [FIRSTNAME],
    [LASTNAME],
    [ADDRESS],
    [BIRTHDAY],
    [ACCOUNT_START_DATE],
    [ACCOUNT_END_DATE],
    [IS_MEMBER]
FROM
    STAGING_RIDER;

GO
SELECT
    TOP 10 *
FROM
    [DBO].[RIDER_DIM];