--CREATE STATION_DIM TABLE
IF OBJECT_ID('DBO.STATION_DIM') IS NOT NULL BEGIN DROP EXTERNAL TABLE DBO.STATION_DIM;

END CREATE EXTERNAL TABLE [DBO].[STATION_DIM] WITH (
    LOCATION = 'Star_schema/STATION_DIM',
    DATA_SOURCE = [AzureStorage],
    FILE_FORMAT = [TextFileFormat]
) AS
SELECT
    [STATION_ID],
    [NAME],
    [LATITUDE],
    [LONGITUDE]
FROM
    STAGING_STATION;

SELECT
    TOP 10 *
FROM
    DBO.STATION_DIM;