--CREATE TRIP_FACT TABLE
IF OBJECT_ID('DBO.TRIP_FACT') IS NOT NULL BEGIN DROP EXTERNAL TABLE DBO.TRIP_FACT;

END CREATE EXTERNAL TABLE [DBO].[TRIP_FACT] WITH (
    LOCATION = 'Star_schema/TRIP_FACT',
    DATA_SOURCE = [AzureStorage],
    FILE_FORMAT = [TextFileFormat]
) AS
SELECT
    ST.TRIP_ID,
    ST.RIDER_ID,
    ST.START_AT,
    ST.ENDED_AT,
    ST.START_AT,
    ST.ENDED_AT,
    ST.RIDEABLE_TYPE,
    DATEDIFF(HOUR, ST.START_AT, ST.ENDED_AT) AS DURATION,
    DATEDIFF(YEAR, SR.BIRTHDAY, ST.START_AT) AS RIDER_AGE
FROM
    STAGING_TRIP AS ST
    JOIN STAGING_RIDER SR ON SR.RIDER_ID = ST.RIDER_ID;

SELECT
    TOP 10 *
FROM
    DBO.TRIP_FACT;